(function() {var implementors = {};
implementors["inkwell"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"inkwell/targets/struct.InitializationConfig.html\" title=\"struct inkwell::targets::InitializationConfig\">InitializationConfig</a>",synthetic:false,types:["inkwell::targets::InitializationConfig"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"enum\" href=\"inkwell/enum.OptimizationLevel.html\" title=\"enum inkwell::OptimizationLevel\">OptimizationLevel</a>",synthetic:false,types:["inkwell::OptimizationLevel"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"enum\" href=\"inkwell/enum.GlobalVisibility.html\" title=\"enum inkwell::GlobalVisibility\">GlobalVisibility</a>",synthetic:false,types:["inkwell::GlobalVisibility"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"enum\" href=\"inkwell/enum.DLLStorageClass.html\" title=\"enum inkwell::DLLStorageClass\">DLLStorageClass</a>",synthetic:false,types:["inkwell::DLLStorageClass"]},];
implementors["quote"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"quote/struct.Tokens.html\" title=\"struct quote::Tokens\">Tokens</a>",synthetic:false,types:["quote::tokens::Tokens"]},];
implementors["syn"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"syn/struct.Generics.html\" title=\"struct syn::Generics\">Generics</a>",synthetic:false,types:["syn::generics::Generics"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"syn/struct.WhereClause.html\" title=\"struct syn::WhereClause\">WhereClause</a>",synthetic:false,types:["syn::generics::WhereClause"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"syn/struct.AngleBracketedParameterData.html\" title=\"struct syn::AngleBracketedParameterData\">AngleBracketedParameterData</a>",synthetic:false,types:["syn::ty::AngleBracketedParameterData"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
